[2022-02-12 20:35:38,859] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_dag.ingest manual__2022-02-12T20:35:35.812141+00:00 [queued]>
[2022-02-12 20:35:38,871] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_dag.ingest manual__2022-02-12T20:35:35.812141+00:00 [queued]>
[2022-02-12 20:35:38,872] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 20:35:38,872] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-12 20:35:38,872] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 20:35:38,886] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2022-02-12 20:35:35.812141+00:00
[2022-02-12 20:35:38,929] {standard_task_runner.py:52} INFO - Started process 2463 to run task
[2022-02-12 20:35:38,935] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'ingest', 'manual__2022-02-12T20:35:35.812141+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpeqpe37_c', '--error-file', '/tmp/tmppe4ieahl']
[2022-02-12 20:35:38,937] {standard_task_runner.py:77} INFO - Job 172: Subtask ingest
[2022-02-12 20:35:39,013] {logging_mixin.py:109} INFO - Running <TaskInstance: test_dag.ingest manual__2022-02-12T20:35:35.812141+00:00 [running]> on host 905601e5fedb
[2022-02-12 20:35:39,085] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-12 20:35:39,114] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T20:35:35.812141+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T20:35:35.812141+00:00
[2022-02-12 20:35:39,115] {logging_mixin.py:109} INFO - yellow_taxi_2022_02 /opt/***/yellow_tripdata_2022-02.csv 2022-02-12T20:35:35.812141+00:00
[2022-02-12 20:35:39,128] {logging_mixin.py:109} INFO - connection established successfully, inserting data...
[2022-02-12 20:35:39,137] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 22, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-02-12 20:35:39,159] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=test_dag, task_id=ingest, execution_date=20220212T203535, start_date=20220212T203538, end_date=20220212T203539
[2022-02-12 20:35:39,178] {standard_task_runner.py:92} ERROR - Failed to execute job 172 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 22, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-02-12 20:35:39,226] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-12 20:35:39,274] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
